### ISSUE TITLE
Mäleta mind

### ISSUE THREAD

**Issue by Raunts26** [Raunts26/php-ruhmatoo-projekt#3]
Logimisel sessiooni mäletamine, eraldi checkbox

**Comment by Raunts26** [comment]
@romilrobtsenkov Kas küpsiste kasutamine on piisavalt turvaliseks tehtud või tasuks millelegi veel tähelepanu pöörata?

**Comment by romilrobtsenkov** [comment]
Tegelikult see ei ole nii turvaline. Kõige sagedasem lähenemine on see, et kui sa alustad serveris sessiooni (session_start()), siis sa tekitad pika random id ja salvestad selle andmebaasi ja küpsisesse. andmebaasi eraldi tabelisse salvestad veel sellele sessiooni id'le ka muu nt kasutaja id.

Kui kasutaja vahepeal paneb brauseri kinni ja uuesti avaba - nüüd kui kasutajal on küpsis siis sa kontrollid kas see random id on andmebaasis olemas sessiooni tabelis olemas ja tekitad sessiooni tagasi pannes sinna andmebaasis hoitud andmed: kasutaja id jms.
